ruleset:
  label_and_comment_help_questions:
    name: "Label & comment on issues with help in title or description"
    events: [ issues ]
    label: question
    when:
      - title matches "/help/i" or body matches "/help/i"
      - action = "opened" or action = "reopened"
    comment: >
      Hi @{{ user.login }}


      The issue tracker is for reporting bugs only. If this is a request
      for help with a challenge, please use the [help chat room](https://gitter.im/FreeCodeCamp/Help)
      or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help
      with a specific challenge.


      If this is the case, please close this issue.


      Happy Coding.
