platform:
  - x64
image: ubuntu

skip_branch_with_pr: false

skip_commits:
  files:
    - .github/**
    - api-server/**
    - curriculum/**
    - docs/**
    - news/**
    - public/**
    - seed/**
    - tools/**
    - "./*.md"

environment:
  nodejs_version: "8"

# Install scripts. (runs after repo cloning)
install:
  - echo This client build is built on %buildon% and the commit tag is %APPVEYOR_REPO_TAG% and the tag is %APPVEYOR_REPO_TAG_NAME%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - refreshenv
  - echo we are running on %PLATFORM%
  - node --version
  - npm install
  - npm test

build_script:
  - cd client
  - npm run build

deploy: off
