platform: x64
image: ubuntu

environment:
  nodejs_version: "8"

skip_branch_with_pr: false

skip_commits:
  files:
    - .github/**
    - api-server/**
    - curriculum/**
    - docs/**
    - news/**
    - public/**
    - seed/**
    - tools/**
    - "./*.md"

# Install scripts. (runs after repo cloning)
install:
  - sh: nvm install $nodejs_version
  - node --version
  - npm install
  - npm test

build_script:
  - cd client
  - npm run build

deploy: off
