trigger:
  batch: true
  branches:
    include:
      - production-*
pr: none

pool:
  name: Hosted macOS
  demands: npm

steps:
  - task: NodeTool@0
    displayName: 'Use Node 10.x'
    inputs:
      versionSpec: 10.x

  - script: npm ci
    displayName: 'Install npm dependencies'

  - script: npm run build
    workingDirectory: client
    displayName: 'Build the client'
    env:
      NODE_ENV: production
      LOCALE: $(LOCALE)
      NEWS_LOCATION: $(NEWS_LOCATION)
      API_LOCATION: $(API_LOCATION)
      FORUM_LOCATION: $(FORUM_LOCATION)
      ROLLBAR_CLIENT_ID: $(ROLLBAR_CLIENT_ID)
      STRIPE_PUBLIC_KEY: $(STRIPE_PUBLIC_KEY)
