trigger:
  batch: true
  branches:
    include:
      - production-*

pr: none

pool:
  name: Hosted macOS
  demands: npm

steps:
  - task: NodeTool@0
    displayName: Use Node 10.x
    inputs:
      versionSpec: 10.x

  - script: npm ci
    displayName: Install npm dependencies

  - script: npm run build
    displayName: Build the client
    workingDirectory: client
    env:
      NODE_ENV: production
      LOCALE: $(LOCALE)
      NEWS_LOCATION: $(NEWS_LOCATION)
      API_LOCATION: $(API_LOCATION)
      FORUM_LOCATION: $(FORUM_LOCATION)
      ROLLBAR_CLIENT_ID: $(ROLLBAR_CLIENT_ID)
      STRIPE_PUBLIC_KEY: $(STRIPE_PUBLIC_KEY)

  - task: ArchiveFiles@2
    displayName: Create archive file
    inputs:
      rootFolderOrFile: '$(Agent.BuildDirectory)/s/client/public'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: Publish archive file
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: build-archive
