"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path_env": "CROWDIN_BASE_PATH"
"base_url_env": "CROWDIN_BASE_URL"

"preserve_hierarchy": true

files: [
 {
  "source" : "/curriculum/challenges/english/01-responsive-web-design/**/*.md",
  "translation" : "/curriculum/challenges/%language%/01-responsive-web-design/**/%original_file_name%",
  "ignore": [
    "/**/part-[0-9][0-9][0-9].md",
    "/curriculum/challenges/english/[0-9][0-9]-certificates/**/*.*"
  ],
  "update_option": "update_as_unapproved"
 }
]
