"project_id_env": "CROWDIN_PROJECT_ID_DOCS"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path_env": "CROWDIN_BASE_PATH"
"base_url_env": "CROWDIN_BASE_URL"

"preserve_hierarchy": true

files: [
 {
  "source" : "/*.md",
  "translation" : "/i18n/%language%/%original_file_name%",

  "ignore" : [
    "_coverpage.md",
    "_navbar.md",
    "_translations.md",
    "README.md",
  ],

  # "languages_mapping" : {
  #     "language" : {

  #     }
  #   },

  "update_option": "update_without_changes"
 }
]
