name: CI - Create CodeSee Maps
on:
  workflow_dispatch:
  schedule:
    - cron: '25 0/12 * * 1-5' # Build once every 12 hours, starting at 25 minutes past the hour (UTC)

  pull_request_target:
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
    types: [opened, synchronize, reopened]

permissions: read-all

jobs:
  codesee:
    runs-on: ubuntu-20.04
    if: ${{ github.actor != 'renovate[bot]' && github.actor != 'camperbot' }}
    continue-on-error: true
    name: Analyze the repo with CodeSee
    steps:
      - uses: Codesee-io/codesee-action@23829afb4f274fd69e1b51558f6f08ae267e443c # v2
        with:
          codesee-token: ${{ secrets.CODESEE_ARCH_DIAG_API_TOKEN }}
