name: Crowdin Client UI Download
on:
  workflow_dispatch: 

jobs:

  i18n-download-client-ui-translations:
    name: Client
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Crowdin Download
        uses: crowdin/github-action@master
        # options: https://github.com/crowdin/github-action/blob/master/action.yml
        with:
          # uploads
          upload_sources: false
          upload_translations: false
          auto_approve_imported: false
          import_eq_suggestions: false

          # downloads
          download_translations: true
          skip_untranslated_files: true
          export_only_approved: true

          commit_message: 'chore(i8n,client): processed translations'

          # pull-request
          localization_branch_name: i18n-sync-client-processed-translations
          create_pull_request: false
          pull_request_title: 'chore(i18n,client): Processed translations from crowdin'
          pull_request_body: ''
          pull_request_labels: 'scope: i18n, platform: client, crowdin-sync'

          # global options
          config: './client/i18n/locales/crowdin.yml'
          base_url: ${{ secrets.CROWDIN_BASE_URL_FCC }}

          # Uncomment below to debug
          # dryrun_action: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_CLIENT }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
