name: GitHub - Label PRs
on:
  - pull_request_target

permissions:
  contents: read

jobs:
  triage:
    permissions:
      # for actions/labeler to determine modified files
      contents: read
      # for actions/labeler to add labels to PRs
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@0967ca812e7fdc8f5f71402a1b486d5bd061fe20 # v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
