name: GitHub - Label PRs
on:
  - pull_request_target

permissions:
  contents: read

jobs:
  triage:
    permissions:
      # for actions/labeler to determine modified files
      contents: read
      # for actions/labeler to add labels to PRs
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
