name: i18n - Curriculum PR Validation
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Validate i18n Builds
    # run only on PRs that camperbot opens with title that matches the curriculum sync
    if: ${{ github.event.pull_request.user.login == 'camperbot' && contains(github.event.pull_request.title, 'chore(i18n,learn)') }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Set freeCodeCamp Environment Variables
        run: cp sample.env .env

      - name: Install Dependencies
        run: pnpm install

      - name: Validate Challenge Files
        id: validate
        run: pnpm run audit-challenges

      - name: Create Comment
        # Run if the validate challenge files step fails, specifically. Note that we need the failure() call for this step to trigger if the action fails.
        if: ${{ failure() && steps.validate.conclusion == 'failure' }}
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          github-token: ${{secrets.CAMPERBOT_NO_TRANSLATE}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Hey @freecodecamp/i18n, it looks like we have new English curriculum files that need to be translated."
            })
