name: i18n - Build Validation
on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Validate i18n Builds
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set freeCodeCamp Environment Variables
        run: cp sample.env .env

      - name: Install Dependencies
        run: npm ci

      - name: Validate Challenge Files
        run: npm run audit-challenges
