name: GitHub - Label PRs
on:
  - pull_request_target

permissions:
  contents: read

jobs:
  triage:
    permissions:
      # for actions/labeler to determine modified files
      contents: read
      # for actions/labeler to add labels to PRs
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@2f7477e3004bdfe4bba501d76fae0d81f6eac775 # tag=v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
