name: CI - Unused Exports, Types and Files
env:
  NODE_OPTIONS: '--max_old_space_size=6144'
on:
  schedule:
    # runs every monday at 08:45 UTC
    - cron: '45 8 * * 1'

permissions:
  contents: read

jobs:
  lint:
    name: Find Unused
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Environment variables
        run: |
          cp sample.env .env
          cat .env

      - name: Run Checks
        run: |
          echo npm version $(npm -v)
          npm ci
          npm run knip
