name: CI - Node.js Test Upcoming
on:
  push:
    branches:
      # Treat the below branches as special case for working on workflows
      - actions-**
      - upcoming-**
  schedule:
    # run this Action every 14 days
    - cron: '0 * */14 * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set Environment variables
        run: |
          cp sample.env .env
          echo 'SHOW_UPCOMING_CHANGES=true' >> .env
          echo 'SHOW_NEW_CURRICULUM=true' >> .env
          cat .env

      - name: Lint Source Files
        run: |
          npm ci
          npm run create:config
          npm i --prefix=curriculum-server
          npm i --prefix=web
          npm run build:curriculum
          npm run lint

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Environment variables
        run: |
          cp sample.env .env
          echo 'SHOW_UPCOMING_CHANGES=true' >> .env
          echo 'SHOW_NEW_CURRICULUM=true' >> .env
          cat .env

      - name: Install Dependencies
        run: |
          npm ci
          npm run create:config
          npm run build:curriculum

      - name: Run Tests
        env:
          NODE_OPTIONS: '--max_old_space_size=6144'
        run: npm test
