name: Github - Welcome First-timers
on:
  pull_request:
    types: [opened, closed]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/welcome@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIRST_PR_MERGED: |
            #### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

            Hi @{{ author }},

            Thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

            Cheers & happy contributing!
